# -*- coding: utf-8 -*-
"""Q1KMHierachicalClusteringASS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yuertFxyLNyGP7QnBxc0hflJgUpo4c_k
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

ews = pd.read_csv("/content/EastWestAirlinesConv.csv")
ews.head()

ews.drop(['ID#'], axis=1)

#Normalization function
scaler = StandardScaler()
scaled_ews_df = scaler.fit_transform(ews.iloc[:,1:])

wcss=[]
for i in range(1,11):
  kmeans = KMeans(n_clusters=i,random_state=0)
  kmeans.fit(scaled_ews_df)
  wcss.append(kmeans.inertia_)

plt.plot(range(1,11),wcss)
plt.title('ELbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('wcss')
plt.show()

clusters_new = KMeans(6,random_state=42) # 42 to keep randomisation consistent
clusters_new.fit(scaled_ews_df)

clusters_new.labels_

ews['clusterID'] = clusters_new.labels_

ews

ews.groupby('clusterID').agg(['mean']).reset_index()

"""Hence cluster ID = 1 has highest Balance avg"""

